/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bkav.portlet.article.link.service.base;

import com.bkav.portlet.article.link.model.ArticleLinkEntry;
import com.bkav.portlet.article.link.service.ArticleLinkEntryLocalService;
import com.bkav.portlet.article.link.service.ArticleLinkEntryService;
import com.bkav.portlet.article.link.service.persistence.ArticleLinkEntryPersistence;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.bean.IdentifiableBean;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.model.PersistedModel;
import com.liferay.portal.service.BaseLocalServiceImpl;
import com.liferay.portal.service.PersistedModelLocalServiceRegistryUtil;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the article link entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.bkav.portlet.article.link.service.impl.ArticleLinkEntryLocalServiceImpl}.
 * </p>
 *
 * @author quangcv
 * @see com.bkav.portlet.article.link.service.impl.ArticleLinkEntryLocalServiceImpl
 * @see com.bkav.portlet.article.link.service.ArticleLinkEntryLocalServiceUtil
 * @generated
 */
public abstract class ArticleLinkEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements ArticleLinkEntryLocalService,
		IdentifiableBean {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.bkav.portlet.article.link.service.ArticleLinkEntryLocalServiceUtil} to access the article link entry local service.
	 */

	/**
	 * Adds the article link entry to the database. Also notifies the appropriate model listeners.
	 *
	 * @param articleLinkEntry the article link entry
	 * @return the article link entry that was added
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public ArticleLinkEntry addArticleLinkEntry(
		ArticleLinkEntry articleLinkEntry) throws SystemException {
		articleLinkEntry.setNew(true);

		return articleLinkEntryPersistence.update(articleLinkEntry, false);
	}

	/**
	 * Creates a new article link entry with the primary key. Does not add the article link entry to the database.
	 *
	 * @param entryId the primary key for the new article link entry
	 * @return the new article link entry
	 */
	public ArticleLinkEntry createArticleLinkEntry(long entryId) {
		return articleLinkEntryPersistence.create(entryId);
	}

	/**
	 * Deletes the article link entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param entryId the primary key of the article link entry
	 * @return the article link entry that was removed
	 * @throws PortalException if a article link entry with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public ArticleLinkEntry deleteArticleLinkEntry(long entryId)
		throws PortalException, SystemException {
		return articleLinkEntryPersistence.remove(entryId);
	}

	/**
	 * Deletes the article link entry from the database. Also notifies the appropriate model listeners.
	 *
	 * @param articleLinkEntry the article link entry
	 * @return the article link entry that was removed
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.DELETE)
	public ArticleLinkEntry deleteArticleLinkEntry(
		ArticleLinkEntry articleLinkEntry) throws SystemException {
		return articleLinkEntryPersistence.remove(articleLinkEntry);
	}

	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(ArticleLinkEntry.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return articleLinkEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return articleLinkEntryPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return articleLinkEntryPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return articleLinkEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	public ArticleLinkEntry fetchArticleLinkEntry(long entryId)
		throws SystemException {
		return articleLinkEntryPersistence.fetchByPrimaryKey(entryId);
	}

	/**
	 * Returns the article link entry with the primary key.
	 *
	 * @param entryId the primary key of the article link entry
	 * @return the article link entry
	 * @throws PortalException if a article link entry with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public ArticleLinkEntry getArticleLinkEntry(long entryId)
		throws PortalException, SystemException {
		return articleLinkEntryPersistence.findByPrimaryKey(entryId);
	}

	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException, SystemException {
		return articleLinkEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the article link entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of article link entries
	 * @param end the upper bound of the range of article link entries (not inclusive)
	 * @return the range of article link entries
	 * @throws SystemException if a system exception occurred
	 */
	public List<ArticleLinkEntry> getArticleLinkEntries(int start, int end)
		throws SystemException {
		return articleLinkEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of article link entries.
	 *
	 * @return the number of article link entries
	 * @throws SystemException if a system exception occurred
	 */
	public int getArticleLinkEntriesCount() throws SystemException {
		return articleLinkEntryPersistence.countAll();
	}

	/**
	 * Updates the article link entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param articleLinkEntry the article link entry
	 * @return the article link entry that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public ArticleLinkEntry updateArticleLinkEntry(
		ArticleLinkEntry articleLinkEntry) throws SystemException {
		return updateArticleLinkEntry(articleLinkEntry, true);
	}

	/**
	 * Updates the article link entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param articleLinkEntry the article link entry
	 * @param merge whether to merge the article link entry with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the article link entry that was updated
	 * @throws SystemException if a system exception occurred
	 */
	@Indexable(type = IndexableType.REINDEX)
	public ArticleLinkEntry updateArticleLinkEntry(
		ArticleLinkEntry articleLinkEntry, boolean merge)
		throws SystemException {
		articleLinkEntry.setNew(false);

		return articleLinkEntryPersistence.update(articleLinkEntry, merge);
	}

	/**
	 * Returns the article link entry local service.
	 *
	 * @return the article link entry local service
	 */
	public ArticleLinkEntryLocalService getArticleLinkEntryLocalService() {
		return articleLinkEntryLocalService;
	}

	/**
	 * Sets the article link entry local service.
	 *
	 * @param articleLinkEntryLocalService the article link entry local service
	 */
	public void setArticleLinkEntryLocalService(
		ArticleLinkEntryLocalService articleLinkEntryLocalService) {
		this.articleLinkEntryLocalService = articleLinkEntryLocalService;
	}

	/**
	 * Returns the article link entry remote service.
	 *
	 * @return the article link entry remote service
	 */
	public ArticleLinkEntryService getArticleLinkEntryService() {
		return articleLinkEntryService;
	}

	/**
	 * Sets the article link entry remote service.
	 *
	 * @param articleLinkEntryService the article link entry remote service
	 */
	public void setArticleLinkEntryService(
		ArticleLinkEntryService articleLinkEntryService) {
		this.articleLinkEntryService = articleLinkEntryService;
	}

	/**
	 * Returns the article link entry persistence.
	 *
	 * @return the article link entry persistence
	 */
	public ArticleLinkEntryPersistence getArticleLinkEntryPersistence() {
		return articleLinkEntryPersistence;
	}

	/**
	 * Sets the article link entry persistence.
	 *
	 * @param articleLinkEntryPersistence the article link entry persistence
	 */
	public void setArticleLinkEntryPersistence(
		ArticleLinkEntryPersistence articleLinkEntryPersistence) {
		this.articleLinkEntryPersistence = articleLinkEntryPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Returns the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		PersistedModelLocalServiceRegistryUtil.register("com.bkav.portlet.article.link.model.ArticleLinkEntry",
			articleLinkEntryLocalService);
	}

	public void destroy() {
		PersistedModelLocalServiceRegistryUtil.unregister(
			"com.bkav.portlet.article.link.model.ArticleLinkEntry");
	}

	/**
	 * Returns the Spring bean ID for this bean.
	 *
	 * @return the Spring bean ID for this bean
	 */
	public String getBeanIdentifier() {
		return _beanIdentifier;
	}

	/**
	 * Sets the Spring bean ID for this bean.
	 *
	 * @param beanIdentifier the Spring bean ID for this bean
	 */
	public void setBeanIdentifier(String beanIdentifier) {
		_beanIdentifier = beanIdentifier;
	}

	public Object invokeMethod(String name, String[] parameterTypes,
		Object[] arguments) throws Throwable {
		return _clpInvoker.invokeMethod(name, parameterTypes, arguments);
	}

	protected Class<?> getModelClass() {
		return ArticleLinkEntry.class;
	}

	protected String getModelClassName() {
		return ArticleLinkEntry.class.getName();
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = articleLinkEntryPersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = ArticleLinkEntryLocalService.class)
	protected ArticleLinkEntryLocalService articleLinkEntryLocalService;
	@BeanReference(type = ArticleLinkEntryService.class)
	protected ArticleLinkEntryService articleLinkEntryService;
	@BeanReference(type = ArticleLinkEntryPersistence.class)
	protected ArticleLinkEntryPersistence articleLinkEntryPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	private String _beanIdentifier;
	private ArticleLinkEntryLocalServiceClpInvoker _clpInvoker = new ArticleLinkEntryLocalServiceClpInvoker();
}